"use client";

import React, { useEffect, useRef, useState } from "react";
import { Music, Volume2, VolumeX, Pause, Play, Info } from "lucide-react";
import { cn } from "@/lib/utils";

interface BGMPlayerProps {
  status: string;
  audioPath?: string;
}

export function BGMPlayer({ status, audioPath = "/audio/quiz_bgm.mp3" }: BGMPlayerProps) {
  const [isPlaying, setIsPlaying] = useState(false);
  const [isMuted, setIsMuted] = useState(false);
  const [volume, setVolume] = useState(0.5); // 0.0 ~ 1.0
  const [showCredits, setShowCredits] = useState(false);
  
  const audioRef = useRef<HTMLAudioElement | null>(null);
  const fadeIntervalRef = useRef<NodeJS.Timeout | null>(null);

  // 초기 설정
  useEffect(() => {
    const audio = new Audio(audioPath);
    audio.loop = true;
    audio.volume = 0;
    audioRef.current = audio;

    return () => {
      audio.pause();
      if (fadeIntervalRef.current) clearInterval(fadeIntervalRef.current);
    };
  }, [audioPath]);

  // 상태 변화 감지
  useEffect(() => {
    if (!audioRef.current) return;

    if (status === "PLAYING") {
      fadeIn();
    } else if (status === "RESULT" || status === "ENDED") {
      fadeOut();
    }
  }, [status]);

  const fadeIn = () => {
    const audio = audioRef.current;
    if (!audio) return;
    if (fadeIntervalRef.current) clearInterval(fadeIntervalRef.current);

    audio.play().catch(() => {
      console.warn("Autoplay blocked. User interaction needed.");
    });

    let currentVol = audio.volume;
    fadeIntervalRef.current = setInterval(() => {
      currentVol = Math.min(volume, currentVol + 0.05);
      audio.volume = currentVol;
      if (currentVol >= volume) {
        if (fadeIntervalRef.current) clearInterval(fadeIntervalRef.current);
      }
    }, 100);
  };

  const fadeOut = () => {
    const audio = audioRef.current;
    if (!audio) return;
    if (fadeIntervalRef.current) clearInterval(fadeIntervalRef.current);

    let currentVol = audio.volume;
    fadeIntervalRef.current = setInterval(() => {
      currentVol = Math.max(0, currentVol - 0.05);
      audio.volume = currentVol;
      if (currentVol <= 0) {
        audio.pause();
        if (fadeIntervalRef.current) clearInterval(fadeIntervalRef.current);
      }
    }, 100);
  };

  const togglePlay = () => {
    const audio = audioRef.current;
    if (!audio) return;
    if (isPlaying) {
      audio.pause();
      setIsPlaying(false);
    } else {
      audio.play().catch(() => {});
      audio.volume = volume;
      setIsPlaying(true);
    }
  };

  const toggleMute = () => {
    const audio = audioRef.current;
    if (!audio) return;
    audio.muted = !isMuted;
    setIsMuted(!isMuted);
  };

  return (
    <div className="fixed bottom-6 right-6 z-[200] flex flex-col items-end gap-3">
      {/* Credits Panel */}
      {showCredits && (
        <div className="bg-white/95 backdrop-blur-md border-2 border-indigo-200 p-4 rounded-2xl shadow-2xl max-w-xs animate-in slide-in-from-bottom-4 duration-300">
          <div className="flex justify-between items-start mb-2">
            <h4 className="font-black text-indigo-900 text-sm">Music Credits</h4>
            <button onClick={() => setShowCredits(false)} className="text-gray-400 hover:text-gray-600">✕</button>
          </div>
          <div className="text-[10px] text-gray-600 space-y-1 leading-tight">
            <p className="font-bold">Provided to YouTube by DistroKid</p>
            <p>oriental beat "거문((검은黑))(black) 국악비트 거문고비트 · TaWoo</p>
            <p>℗ 11014098 Records DK</p>
            <p>Released on: 2025-12-11</p>
            <p>Auto-generated by YouTube.</p>
          </div>
        </div>
      )}

      {/* Main Control Bar */}
      <div className="flex items-center gap-2 bg-white/80 backdrop-blur-md border-2 border-indigo-100 p-2 rounded-full shadow-lg ring-4 ring-white/50">
        <button 
          onClick={() => setShowCredits(!showCredits)} 
          className={cn(
            "w-10 h-10 rounded-full flex items-center justify-center transition-all", 
            showCredits ? "bg-indigo-600 text-white" : "bg-indigo-50 text-indigo-600 hover:bg-indigo-100"
          )}
        >
          <Info size={18} />
        </button>

        <div className="h-6 w-px bg-indigo-100 mx-1" />

        <button onClick={togglePlay} className="w-10 h-10 bg-white border border-indigo-50 rounded-full flex items-center justify-center text-indigo-600 hover:scale-110 active:scale-95 transition-all shadow-sm">
          {isPlaying ? <Pause size={18} fill="currentColor" /> : <Play size={18} className="ml-0.5" fill="currentColor" />}
        </button>

        <button onClick={toggleMute} className="w-10 h-10 bg-white border border-indigo-50 rounded-full flex items-center justify-center text-indigo-600 hover:scale-110 active:scale-95 transition-all shadow-sm">
          {isMuted ? <VolumeX size={18} /> : <Volume2 size={18} />}
        </button>
        
        <div className="flex items-center gap-2 px-3">
          <Music size={16} className={cn("text-indigo-400", isPlaying && "animate-spin-slow")} />
          <span className="text-[10px] font-black text-indigo-900 uppercase tracking-widest hidden md:inline">BGM</span>
        </div>
      </div>

      <style jsx>{`
        @keyframes spin-slow { from { transform: rotate(0deg); } to { transform: rotate(360deg); } }
        .animate-spin-slow { animation: spin-slow 8s linear infinite; }
      `}</style>
    </div>
  );
}
